name:       naruto-unison
version:    0.1.0.0
github:     "naruto-unison/naruto-unison"
license:    BSD3
author:     "Naruto Unison"
maintainer: "joshua.n.booth@gmail.com"

library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only) || flag(ci))
    then:
      ghc-options: -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options: -O2
  dependencies:
  - aeson
  - attoparsec
  - base
  - bimap
  - bitwise-enum
  - blaze-html
  - blaze-markup
  - bytestring
  - cache
  - case-insensitive
  - classy-prelude
  - cmark
  - concurrent-hashtable
  - containers
  - data-default
  - esqueleto
  - fast-logger
  - file-embed
  - hjsmin
  - http-client-tls
  - http-conduit
  - http-types
  - mime-mail
  - monad-logger
  - monad-loops
  - mtl
  - multimap
  - mwc-random
  - persistent
  - persistent-postgresql
  - persistent-template
  - primitive
  - random
  - shakespeare
  - template-haskell
  - text
  - time
  - transformers
  - unliftio
  - unordered-containers
  - vector
  - vector-algorithms
  - wai
  - wai-extra
  - wai-logger
  - warp
  - websockets
  - yaml
  - yesod
  - yesod-auth
  - yesod-core
  - yesod-form
  - yesod-static
  - yesod-websockets

executables:
  naruto-unison:
    source-dirs: app/naruto-unison
    main: main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naruto-unison
    - base
    when:
    - condition: flag(library-only)
      buildable: false
    - condition: flag(ci)
      buildable: false
  elm-bridge:
    source-dirs: app/elm-bridge
    main: main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naruto-unison
    - aeson
    - base
    - containers
    - elm-bridge
    - template-haskell
    - text
    when:
    - condition: flag(library-only)
      buildable: false
    - condition: flag(ci)
      buildable: false

tests:
  test-game:
    source-dirs: test/game
    main: Spec.hs
    dependencies:
    - naruto-unison
    - base
    - bitwise-enum
    - hspec
    - hspec-core
    - QuickCheck
    - transformers
  test-missions:
    source-dirs: test/missions
    main: Spec.hs
    dependencies:
    - naruto-unison
    - base
    - hspec
  test-yesod:
    source-dirs: test/yesod
    main: Spec.hs
    dependencies:
    - naruto-unison
    - base
    - hspec
    - persistent
    - shakespeare
    - transformers
    - yesod
    - yesod-auth
    - yesod-core
    - yesod-test
    when:
    - condition: flag(ci)
      buildable: false

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel".
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
  ci:
    description: Build for use with a continuous integration system.
    manual: false
    default: false

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -ferror-spans
- -funbox-small-strict-fields

default-extensions:
# Manual disabling
- NoStarIsType
# Package-specific
- NoImplicitPrelude
# Removing artificial limitations
- ConstraintKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
# Syntactic sugar
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- RecordWildCards
- ParallelListComp
- TupleSections
- UnicodeSyntax
- ViewPatterns
- MonadComprehensions
- BlockArguments
- MagicHash
# More powerful types
- TypeFamilies
# More powerful deriving
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- ScopedTypeVariables
# Unlikely to be used, but no drawbacks
- BangPatterns
- DefaultSignatures
- EmptyDataDecls
- KindSignatures
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
# - TypeApplications
- TypeOperators
# Literals
- BinaryLiterals
- NegativeLiterals
- NumDecimals
# Unfortunate necessities
- OverloadedStrings
# Here Be Dragons
- ApplicativeDo
- StrictData
- UnboxedTuples
